apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: veni
  name: veni
spec:
  replicas: 2
  selector:
    matchLabels:
      app: veni
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: veni
    spec:
      containers:
      - image: registry.rosish.site/veni:v.1
        name: image
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
